# Generated by Django 3.0.7 on 2020-06-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_information',
            fields=[
                ('clinic_name', models.CharField(help_text="Enter the patient's name", max_length=20, primary_key=True, serialize=False, verbose_name='Patient Name:')),
                ('previous', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='N/A', help_text='Has patient preformed p-EGFR test in Sanomics previously?', max_length=3)),
                ('spid', models.CharField(blank=True, help_text="If yes, Enter the patient's Sanomics Patient ID", max_length=10)),
                ('diagnosis', models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending')], help_text='Diagnosis of Lund Cancer:', max_length=10)),
                ('celltype', models.CharField(blank=True, choices=[('Adenocarcinoma', 'Adenocarcinoma'), ('Squamous Carcinoma', 'Squamous Carcinoma'), ('Adenosquamous Carcinoma', 'Adenosquamous Carcinoma'), ('Others', 'Others')], help_text='If confirmed, Histological Cell Type:', max_length=30)),
                ('other', models.CharField(blank=True, help_text='If choose others, please state:', max_length=30)),
                ('stage', models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=5, verbose_name='Stage of Disease')),
                ('status', models.CharField(blank=True, choices=[('Treatment Naive', 'Treatment Naive'), ('On Chemotherapy', 'On Chemotherapy'), ('On Tyrosine Kinase Inhibitor(s)(TKI)', 'On Tyrosine Kinase Inhibitor(s)(TKI)')], max_length=100, verbose_name='Treatment Status')),
                ('additional', models.CharField(blank=True, default='', max_length=100, verbose_name='Additional Information')),
                ('request', models.CharField(blank=True, choices=[('Exon 19 Deletions + Exon 21 L858R + Exon 20 T790M', 'a) Exon 19 Deletions + Exon 21 L858R + Exon 20 T790M'), ('#Exon 20 C797S(Test for resistance to T790M-targeting EGFR TKI)', 'b) #Exon 20 C797S(Test for resistance to T790M-targeting EGFR TKI)'), ('Exon 19 Deletions + Exon 21 L858R + Exon 20 T790M + #Exon 20 C797S(Test for resistance to T790M-targeting EGFR TKI)', 'a) + b)')], help_text='Remarks: TWO Streck tubes of specimen are required for a) OR a) + b)\n         ONE Streck tuve of specimen is required for b) only', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specimen_type', models.CharField(blank=True, choices=[('Blood', 'Blood'), ('Pleural Fluid', 'Pleural Fluid'), ('others', 'Others')], max_length=20, verbose_name='Specimen Type *')),
                ('other_type', models.CharField(blank=True, help_text='If you choose others, please state:', max_length=30)),
                ('collectiondate', models.CharField(help_text='YYYY/MM/DD', max_length=10, verbose_name='Collection Date *')),
                ('collectiontime', models.CharField(help_text='HH:MM', max_length=5, verbose_name='Collection Time *')),
                ('name', models.CharField(help_text="Enter the patient's name", max_length=30, verbose_name='Full Name *')),
                ('hkid', models.CharField(help_text="Enter the patient's HKID/Passport No.", max_length=20, verbose_name='HKID/National ID/Passport ID *')),
                ('ethnicity', models.CharField(blank=True, help_text="Enter the patient's Ethnicity", max_length=20, verbose_name='Ethnicity ')),
                ('sex', models.CharField(help_text="Enter the patient's sex", max_length=1, verbose_name='Sex *')),
                ('dob', models.DateField(verbose_name='Date of Birth *')),
                ('referral', models.CharField(help_text='Enter the Referral Site', max_length=20, verbose_name='Referral Site *')),
                ('clinicid', models.CharField(blank=True, help_text='Enter the Clinic ID', max_length=10)),
                ('doctor', models.CharField(help_text='Enter the Referral Doctor', max_length=30, verbose_name='Referral Doctor *')),
                ('phone', models.CharField(blank=True, help_text='Enter the phone number', max_length=15)),
                ('fax', models.CharField(blank=True, help_text='Enter the fax number', max_length=30)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Clinic_information')),
            ],
        ),
    ]
