# Generated by Django 3.0.7 on 2020-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='collectiondate',
            field=models.CharField(max_length=20, verbose_name='Collection Date *'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='dob',
            field=models.CharField(max_length=20, verbose_name='Date of Birth *'),
        ),
    ]
