# Generated by Django 3.0.7 on 2020-07-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200630_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M'), ('Prefer not to say', 'Prefer not to say')], help_text="Enter the patient's sex", max_length=20, verbose_name='Sex *'),
        ),
    ]
